### ISSUE TITLE
Unable to change device names

### ISSUE THREAD

**Issue by nano9g** [philippe44/SpotConnect#10]
As long as I'm opening issues…

Using spotraop, I'm trying to change the name of a device. I've tried using both `<friendly-name>` and `<name>`, but the device still shows in Spotify as dev[string of numbers and letters]+, which is different from the ID in the config file. I have also tested it with and without spaces, which doesn’t seem to make a difference. (It isn't working with HomePods or Apple TVs either.)

```
    <device>
        <udn>[id]@Host Name._raop._tcp.local</udn>
        <name></name>
        <friendly_name>My AirPlay Device</friendly_name>
        <enabled>1</enabled>
    </device>
```

No matter what I do, the device list in Spotify is:

```
🔈 HomePod+
🔈 dev[string of numbers and letters]+
```

Is there anything else I should try?

**Comment by philippe44** [comment]
Should be fixed in 0.1.2
