### ISSUE TITLE
Log level options don't appear to have any effect

### ISSUE THREAD

**Issue by nano9g** [philippe44/SpotConnect#11]
When log levels are set via command line or config file, they don't seem to be respected.

I would expect this command to disable the majority of the logging:
```
/var/lib/spoconnect/spotraop-linux-aarch64-static -d all=error
```
Even with that, the log is still full of "I" and "D" messages from the various components.

**Comment by philippe44** [comment]
Isn't it just the logs related to core Spotify events? It's probably due to the cspot component where I can't disable logs
