### ISSUE TITLE
Unable to pair Apple TV HDs

### ISSUE THREAD

**Issue by nano9g** [philippe44/SpotConnect#13]
I have an assortment of Apple TV models and was able to immediately pair the 4K. However, I have been unable to pair the HDs (model A1625). Most of the time, the output looks like this (running with `-l -d all=sdebug`):

```
pick an AppleTV or type "exit" to leave pairing mode

[IP1]      => [ID]@Apple TV 4K._raop._tcp.local
[IP2]      =>  [ID]@Apple TV HD2._raop._tcp.local
[IP3]      =>  [ID]@Apple TV HD1._raop._tcp.local

IP address: [IP3]
[17:02:12.098712] http_parse_simple:961 sock: 15, received Date: Sat, 29 Jul 2023 21:02:12 GMT
[17:02:12.099253] http_parse_simple:961 sock: 15, received Content-Length: 0
[17:02:12.099882] http_parse_simple:961 sock: 15, received Server: AirTunes/695.5.1
enter PIN code displayed on AppleTV: [PIN]
step1 ... verifying pin
please wait 5 seconds...
```
and then it loops back to "pick an AppleTV…"

Occasionally (maybe 1 out of 10 times?) it will say `step2 ... verifying M1` but even then it never comes back with a credential string.

Please let me know what I can do to help figure out what's happening. Thank you as always!

**Comment by philippe44** [comment]
This is the piece of code I hate the most 😄. Can you share the ID of one of your ATV, or at least tell me is there is anything much different compared to the 4K one?

**Comment by philippe44** [comment]
I've found and older ATV A1625 which had the pairing issue as well. Version 0.1.3 fixes it for these, let me know how it works for you
