### ISSUE TITLE
Binaries for release 0.2.7

### ISSUE THREAD

**Issue by GioF71** [philippe44/SpotConnect#21]
Hello @philippe44 and thank you for the great work.
Is there a chance that the latest 0.2.7 does not include x86_64 linux versions, which 0.2.6 was including?
Thank you

**Comment by philippe44** [comment]
Probably an oversight. I've rebuilt and uploaded them

**Comment by GioF71** [comment]
Thank you!

**Comment by GioF71** [comment]
Sorry to bother you again, but it seems to me that the x86_64 linux binary is missing also for the 'raop' version.
Thanks a lot for your great work!
