### ISSUE TITLE
[spotraop] Cannot run non-static build on docker using debian:stable as base image

### ISSUE THREAD

**Issue by GioF71** [philippe44/SpotConnect#23]
Hello, I am experiencing a problem with spotraop when using the non-static binaries in a docker image.
At least for the x86_64 (linux) platform, I get:

```
spotconnect-airplay    | Using SpotConnect raop version [0.3.2]
spotconnect-airplay    | VORBIS_BITRATE not set, using 320
spotconnect-airplay    | Command Line: [/app/bin/spotraop-linux -r 320 -x /config/config.xml -I -j -k -Z]
spotconnect-airplay    | [13:05:39.065] main:1199 Starting spotraop version: v0.3.2 (Oct 18 2023 @ 17:31:23)
spotconnect-airplay    | 
spotconnect-airplay    | [13:05:39.067] Start:926 Cannot load SSL libraries
spotconnect-airplay    | [13:05:39.067] main:1263 Cannot start, exiting

```
when running the binary on a vanilla debian:stable image.
Installing openssl did not help.
The corresponding non-static upnp version of spotconnect runs ok under the same conditions.

I cannot figure out what I am doing wrong, can you please help me troubleshoot the issue?

Thank you.

**Comment by philippe44** [comment]
I don't think you're doing anything "wrong" but your debian does not have any of the following ssl libraries
```
static char *LIBSSL[] 		= {
			"libssl.so",
			"libssl.so.1.1.1",
			"libssl.so.1.1.0",
			"libssl.so.1.1",
			"libssl.so.1.0.2",
			"libssl.so.1.0.1",
			"libssl.so.1.0.0", NULL };
static char *LIBCRYPTO[] 	= {
			"libcrypto.so",
			"libcrypto.so.1.1.1",
			"libcrypto.so.1.1.0",
			"libcrypto.so.1.1",
			"libcrypto.so.1.0.2",
			"libcrypto.so.1.0.1",
			"libcrypto.so.1.0.0", NULL };
```

**Comment by GioF71** [comment]
Thank you. For the moment I will enforce the use of the static variants for spotraop.

**Comment by philippe44** [comment]
oh, I forgot that discussion 😄. Maybe be if you tell me what are the libraries installed on your system, I can make a change.

**Comment by GioF71** [comment]
Hello @philippe44, thank you, I followed up on your ticket [here](https://github.com/GioF71/spotconnect-airplay-docker/issues/1)

**Comment by GioF71** [comment]
Hello @nano9g, please try the latest image!

**Comment by philippe44** [comment]
Thanks!
