### ISSUE TITLE
kernel too old on Synology

### ISSUE THREAD

**Issue by NGDM** [philippe44/SpotConnect#24]
I'm getting this log output when running this project through Docker on my Synology DS916+ (DSM 7.1.1-42962 Update 6)
```
Ensuring user with uid:[1045] gid:[65539] exists ...
Group with gid [65539] name [spotc] already exists.
user with uid [1045] name [spotc] already exists.
Using SpotConnect raop version [0.4.1]
Command Line: [/app/bin/spotraop-linux-static -r 320 -x /config/config.xml -I -j -k -Z]
Segmentation fault (core dumped)
```

When I attach to the console and try to run the command myself, I get this output:
```
root@SpotConnect:/# /app/bin/spotraop-linux-static -r 320 -x /config/config.xml -I -j -k -Z 
FATAL: kernel too old
Segmentation fault (core dumped)
```

My kernel version is 3.10.108

Any hope to fix this with some config or change to my Docker env?

**Comment by philippe44** [comment]
What happens with the non-static version?

**Comment by NGDM** [comment]
```
# /app/bin/spotraop-linux -r 320 -x /config/config.xml -I -j -k -Z 
[22:31:30.872] main:1221 Starting spotraop version: v0.5.0 (Nov 10 2023 @ 22:13:28)
[22:31:30.872] main:1228 

!!!!!!!!!!!!!!!!!! ERROR LOADING CONFIG FILE !!!!!!!!!!!!!!!!!!!!!

[22:31:30.873] Start:945 Cannot load SSL libraries
[22:31:30.873] main:1325 Cannot start, exiting
```
I didn't have a config, but not sure if it needs it. 
I tried creating an empty config file, but still errors out.

What about the SSL libraries?

**Comment by philippe44** [comment]
The config file is not a problem. I was not aware of that work from @GioF71. Normally, if you can find the ssl libraries, you could install them in the same directory. They are libssl.so and libcrypto.so. If you find such libraries with a slightly different name, let me know so I can include them.

**Comment by NGDM** [comment]
Hi @GioF71, just did and it started as expected!
Thanks, I was afraid my vintage Synology Linux kernel was blocking me again, but it's working.

Works as advertised. My AirPlay (1 & 2) devices now show as Spotify Connect speakers, and also keep playing even without the initiating device.
Great stuff!

**Comment by GioF71** [comment]
Biggest thank you should go to @philippe44 who put me in the right direction.
Consider starring the repos if that doesn't bother you :-)
Cheers
