### ISSUE TITLE
[Release 0.9.1] Linux x86_64 binaries missing?

### ISSUE THREAD

**Issue by GioF71** [philippe44/SpotConnect#34]
Hello, it looks to me that x86_64 linux binaries are missing from the latest release 0.9.1
Thank you for your attention.
Giovanni

**Comment by philippe44** [comment]
Should be fine now

**Comment by GioF71** [comment]
Thank you, I will retry tomorrow!

**Comment by GioF71** [comment]
It's ok now, thank you very much.
Closing the issue.
