### ISSUE TITLE
use Releases

### ISSUE THREAD

**Issue by lollilol** [philippe44/SpotConnect#4]
very cool project, but don't you think it would be smarter to use the github releases for the releases? I mean you can still put the compiled version in the repo files if you want, or don't you do it because of a specific reason?

**Comment by philippe44** [comment]
No reason. This is what I do for my AirConnect project so I can't do the same here

**Comment by lollilol** [comment]
i don't get it lol

**Comment by philippe44** [comment]
Well, I mean I CAN do the same here
