### ISSUE TITLE
volume_feedback / volume_mode what options are there and what do they mean?

### ISSUE THREAD

**Issue by zyxep** [philippe44/SpotConnect#42]
Hey,

Love this app, it's really awesome.
I have 1 question, when playing to my homepod mini, the audio level is always 0 (off) as soon as i connect and play.
I can see that from the generated config file there are 2 common options.
```xml
<volume_feedback>1></volume_feedback>
<volume_mode>2</volume_mode>
```
What does these 2 mean and what options are there to e.g. keep last audio level from the homepod?

**Comment by philippe44** [comment]
volume_mode is the method used to control volume. 2 is to use the AirPlay volume command, 1 is to use software volume inside SpotRaop (not recommended). 

Now, the volume should be restored upon connection. THere might be something specific to HomePod mini, but I don't have these unfortunately so I can't test
