### ISSUE TITLE
[Question] Support for Chromecast

### ISSUE THREAD

**Issue by juanmanjarres** [philippe44/SpotConnect#44]
Hi, first of all thank you for the plugins! I use AirConnect quite often and it's really handy. I was just wondering if it's possible at all to make a version of SpotConnect that has support for Chromecast instead of Spotify Connect? Basically AirConnect but reversed. I use a LG TV often that only supports AirPlay and I was wondering if that was possible

**Comment by philippe44** [comment]
No it's not possible due to the way CC works and Google protects application running inside

**Comment by juanmanjarres** [comment]
Makes sense, thank you nonetheless!
