### ISSUE TITLE
Cannot build due to missing commit in cspot

### ISSUE THREAD

**Issue by fanzeyi** [philippe44/SpotConnect#45]
Hi,

It looks like 0.9.2 of this repository references a commit `c2213c6a38752fc00e0a2f0b3682aaa04ccd3b51` in https://github.com/philippe44/cspot that is not updated (or deleted?). That repo doesn't seem to have any update since 6 months ago.

Can you please update that commit? Thank you!

```
git submodule update --init
warning: redirecting to https://github.com/philippe44/cspot.git/
warning: redirecting to https://github.com/philippe44/cspot.git/
fatal: remote error: upload-pack: not our ref c2213c6a38752fc00e0a2f0b3682aaa04ccd3b51
fatal: Fetched in submodule path 'cspot', but it did not contain c2213c6a38752fc00e0a2f0b3682aaa04ccd3b51. Direct fetching of that commit failed.
```

**Comment by philippe44** [comment]
Just use latest commit
