### ISSUE TITLE
[Question] Why do you exclude some airplay software

### ISSUE THREAD

**Issue by TychoHae** [philippe44/SpotConnect#51]
Thanks for making this nice and useful piece of software.

When experimenting how to make a workaround to spotify connect temporarily not working with spotty in LMS
I noticed this line

glExcludedModels[STR_LEN] = "aircast,airupnp,shairtunes2,airesp32,";

I  managed to get it working with the shairtunes2 plugin and LMS by removing it from the blacklist.

Since all 4 of the blacklisted programs are your own programs I wonder why you blacklisted them.

Sincerely Tycho

**Comment by philippe44** [comment]
Everything that is AirPlay can be used directly by Spotify client.

**Comment by TychoHae** [comment]
Ok , I can indeed use the airplay audio directly by the spotify clients from apple devices  or from linux with pipewire and it's  raop module, but the advantage of using connect is to play make the stream independent of the hardware you are running the client on

**Comment by philippe44** [comment]
To be more precise
- airupnp: use spotupnp instead of airupnp + spotraop
- aircast: AFAIK, all Spotify controller support chromecast on all OS
- airesp32: Spotify is built-in squeezeesp32
- shairtunes2: this is LMS ecosystem, better use Spotty rather convoluted shairtunes2 + spotraop

**Comment by TychoHae** [comment]
Thank you, makes sense , the convoluted spotraop+ shairtunes2 was intended only as stopgap/workarround when the spotify connect  option in Spotty does not work
