### ISSUE TITLE
binaries in the repo

### ISSUE THREAD

**Issue by mterron** [philippe44/SpotConnect#6]
Can you please remove the binaries (included thrice for good measure, once inside a zip file, then again in the `bin` directory and then as object in the `.git/objects` directory) from the repo and move them to releases? 
It's surprising behaviour to try to clone the repo and get a 380MB download that expands to over 600MB when I want to just build 1 arch/os.

For comparison, the repo size without the bins is 428K and with the binaries it is 635.5MB.

```sh
~/SpotConnect # du -sh .
635.5M  . # Due to the .git repo containing all the binaries once again
~/SpotConnect # rm -rf SpotConnect-0.1.0.zip spotupnp/bin spotraop/bin/
~/SpotConnect # du -sh .
381.4M  .
~/SpotConnect # rm -rf .git
~/SpotConnect # du -sh .
428.0K  .
```

**Comment by philippe44** [comment]
I can remove the bin/but the zip will remain
