### ISSUE TITLE
GLIBCXX Error on Raspberry Pi OS

### ISSUE THREAD

**Issue by nano9g** [philippe44/SpotConnect#8]
I’m excited to try SpotConnect, but I’m having difficulty getting it up and running. When I try to run the aarch64 binary, I get this error:
```
./spotraop-linux-aarch64: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./spotraop-linux-aarch64)
```

<br>
Here’s my OS information:

```
$ uname -a
Linux [host] 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

Any ideas on resolving this error?

**Comment by philippe44** [comment]
You can try the -static version for now

**Comment by philippe44** [comment]
Then have a look at my cross-compiler adventure here https://github.com/philippe44/cross-compiling and see toward the end the section on GLIBC and GLIBCXX. I have also various libs included.

**Comment by philippe44** [comment]
Oh, but before are you sure to use the version 0.1.1? There was an issue before that with static build not being truly statics
